---
title: "decision accuracy simulation"
author: "Iris Yocarini"
date: "22 May 2016"
output: html_document
---
#Simulation Decision Accuracy
### Import data
In a different project, this data was simulated. Under 144 different conditions (full factorial model), 500 datasets were simulated with each simulation containing simulated grades from 2000 students. 

```{r}
datasim <- read.csv("~/Rworkspace/simdata/datasetsimulatiespaper", sep="")
str(datasim, list.len=ncol(datasim))
```

### Descriptives

#### Manipulated variables
The 144 conditions were created using a full factorial model of four variables that were manipulated:

* The number of tests were manipulated at `r length(unique(datasim$n))` levels: n = `r unique(datasim$n)`
* The correlation between the tests was manipulated at `r length(unique(datasim$cor))` levels: cor = `r unique(datasim$cor)`
* The average reliability of the tests was manipulated at `r length(unique(datasim$R))` levels: R = `r unique(datasim$R)`
* The number of tests allowed to be retaken were manipulated at `r length(unique(datasim$z))` levels: cor = `r unique(datasim$z)`

#### Decisoin rules